Create Table Assets(AssetId int PRIMARY KEY NOT NULL, 
					ScenarioId int, 
					OrganisationId varchar(50), 
					Name varchar(50), 
					AssetType int,
					PurchaseYear int,
					PurchaseMonth int,
					NoofUnits int,
					CostsperUnit int,
					UsefulLifetime int,
					ResidualValue int,
					DaystoPay int,
					Assumptions varchar(50))
Create Table AssetsValues(AssetValueId int PRIMARY KEY NOT NULL,
						  AssetId int,
						  ScenarioId int,
						  Year int,
						  Month int,
						  AssetValue int,
						  Total int,
						  ValueType int)
Create Table Cogs(CogsId int PRIMARY KEY NOT NULL,
				  OrganisationId varchar(50),
				  ScenarioId int,
				  RevenueId int,
				  Name varchar(100),
				  StartYear int,
				  StartMonth int,
				  CostsinStartMonth int,
				  MonthlyCostChange int,
				  DaystoPay int,
				  InventoryDays int,
				  Assumptions varchar(100))
Create Table CogsValues(CogsValueId int PRIMARY KEY NOT NULL,
						CogsId int,
						ScenarioId int,
						Year int,
						Month int,
						CogsValue int,
						Total int,
						ValueType int)
Create Table FinancingValues(FinancingValueId int PRIMARY KEY NOT NULL,
							FinancingId int,
							ScenarioId int,
							Year int,
							Month int,
							FinancingValue int,
							Total int,
							ValueType int)
Create Table OtherRevenueValues(OtherRevenueValueId int PRIMARY KEY NOT NULL,
								OtherRevenueId int,
								ScenarioId int,
								Year int,
								Month int,
								RevenueValue int,
								Total int,
								ValueType int)
Create Table PersonnelValues(PersonnelValueId int PRIMARY KEY NOT NULL,
							PersonnelId int,
							ScenarioId int,
							Year int,
							Month int,
							PersonnelValue int,
							Total int,
							ValueType int)
Create Table RevenueValues(RevenueValueId int PRIMARY KEY NOT NULL,
							RevenueId int,
							ScenarioId int,
							Year int,
							Month int,
							RevenueValue int,
							Total int,
							ValueType int)
Create Table Role(RoleId varchar(50), RoleName varchar(50))
Create Table Scenario(ScenarioId int PRIMARY KEY NOT NULL,
					  ScenarioName varchar(50),
					  OrganisationId varchar(50),
					  Tax int,
					  StartYear int,
					  ForecastPeriod int,
					  MarketSize int,
					  SAM int,
					  TAM int,
					  SOM int)
Create Table Users(UserId varchar(50) PRIMARY KEY NOT NULL,
					UserRoleId varchar(50),
					FirstName varchar(50),
					LastName varchar(50),
					Email varchar(50),
					Password varchar(50),
					UserStatus int,
					OrganisationId varchar(50),
					ConfirmPassword varchar(50),
					DateofBirth date)
Create Table Financing(FinancingId int PRIMARY KEY NOT NULL,
						ScenarioId int,
						OrganisationId varchar(50),
						Name varchar(50),
						StartYear int,
						StartMonth int,
						FinancingAmount int,
						Assumptions varchar(100),
						InterestPerYear int,
						Payback int,
						FinancingPeriodMonths int,
						FinancingType int)
Create Table Organisation(OrganisationId varchar(50) PRIMARY KEY NOT NULL,
						  Name varchar(50),
						  Website varchar(50),
						  Sector varchar(50),
						  SubSector varchar(50),
						  Description varchar(5000),
						  Country varchar(50),
						  Currency varchar(50),
						  FoundedYear int)
Create Table OtherRevenue(OtherRevenueId int PRIMARY KEY NOT NULL,
							OrganisationId varchar(50),
							ScenarioId int,
							StartYear int,
							StartMonth int,
							RevenueinStartMonth int,
							FrequencyClientIncr int,
							PerClientIncr int,
							DaysPaid int,
							Assumptions varchar(50),
							RevenueName varchar(50),
							RevenueCategory varchar(50))
Create Table Personnel(PersonnelId int PRIMARY KEY NOT NULL,
							OrganisationId varchar(50),
							ScenarioId int,
							StartYear int,
							StartMonth int,
							NoofFTEs int,
							GrossSalary int,
							PerSalaryIncrease int,
							AdditionalEmployeeCosts int,
							Assumptions varchar(50),
							Position varchar(50),
							PersonnelType varchar(50))
Create Table Revenue(RevenueId int PRIMARY KEY NOT NULL,
					OrganisationId varchar(50),
					ScenarioId int,
					StartYear int,
					StartMonth int,
					ClientsInStartMonth int,
					FrequencyClientIncr int,
					PerClientIncr int,
					DaysPaid int,
					UnitsSoldperclientpermonth int,
					PricePerUnit int,
					Assumptions varchar(50),
					RevenueName varchar(50),
					RevenueCategory varchar(50))